openapi: 3.1.0
info:
  title: PubMed論文検索API
  version: "1.0.0"
servers:
  - url: https://pubmed-gpt-action.onrender.com/
paths:
  /search_papers:
    get:
      operationId: searchPapers
      summary: PubMedで論文を検索する
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
          description: 検索したいキーワード
      responses:
        '200':
          description: 検索結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  papers:
                    type: array
                    items:
                      type: object
                      properties:
                        pmid:
                          type: string
                        link:
                          type: string
  /get_metadata:
      get:
        operationId: getMetadata
        summary: Get metadata from Crossref using DOI
        parameters:
          - name: doi
            in: query
            required: true
            schema:
              type: string
            description: DOI（例：10.1038/s41586-020-2649-2）
        responses:
          '200':
            description: Crossref論文情報
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    title:
                      type: string
                    authors:
                      type: array
                      items:
                        type: string
                    journal:
                      type: string
                    published:
                      type: array
                      items:
                        type: string
                    abstract:
                      type: string