openapi: 3.1.0
info:
  title: PubMed論文検索API
  version: "1.0.0"
servers:
  - url: https://pubmed-gpt-action.onrender.com/
paths:
  /search_papers:
    get:
      operationId: searchPapers
      summary: PubMedで論文を検索する
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
          description: 検索したいキーワード
      responses:
        '200':
          description: 検索結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  papers:
                    type: array
                    items:
                      type: object
                      properties:
                        pmid:
                          type: string
                        link:
                          type: string
